title: "카페 등록"
labels: ["cafe-registration"]
body:
  - type: input
    id: cafe_name
    attributes:
      label: 카페명
      description: 카페의 정식 상호명을 입력해주세요
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 선정 이유
      description: 이 카페를 선정한 이유를 설명해주세요
    validations:
      required: true

  - type: input
    id: address
    attributes:
      label: 도로명 주소
      description: 정확한 도로명 주소를 입력해주세요
      placeholder: "서울특별시 강남구 테헤란로 123"
    validations:
      required: true

  - type: input
    id: map_url
    attributes:
      label: 지도 URL
      description: 네이버 지도 URL을 입력해주세요
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: 태그 
      description: 태그를 쉼표(,)로 구분하여 입력해주세요
      placeholder: "로스터리, 베이커리, 테라스, 주차가능"
    validations:
      required: true

  - type: input
    id: region
    attributes:
      label: 필터상 지역
      description: 지역을 입력해주세요
      placeholder: "성수/서울숲"
    validations:
      required: true

  - type: input
    id: station
    attributes:
      label: 역 정보
      description: 가장 가까운 역과 출구 번호를 입력해주세요
      placeholder: "강남역"
    validations:
      required: true

  - type: input
    id: main_image
    attributes:
      label: 메인 이미지
      description: 메인 이미지를 업로드하고 생성된 URL을 입력해주세요
    validations:
      required: true

  - type: textarea
    id: preview_images
    attributes:
      label: 미리보기 이미지
      description: |
        미리보기 이미지 URL들을 한 줄에 하나씩 입력해주세요.
        예시:
        https://example.com/image1.jpg
        https://example.com/image2.jpg
        https://example.com/image3.jpg
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 대표 원두"

  - type: input
    id: bean_name
    attributes:
      label: 원두명
      description: 대표 원두의 이름을 입력해주세요
    validations:
      required: true

  - type: input
    id: flavors
    attributes:
      label: 향미
      description: 향미를 쉼표(,)로 구분하여 입력해주세요
      placeholder: "초콜릿, 견과류, 달콤함"
    validations:
      required: true

  - type: input
    id: origins
    attributes:
      label: 산지
      description: 원두 산지를 쉼표(,)로 구분하여 입력해주세요
      placeholder: "에티오피아, 과테말라"
    validations:
      required: true

  - type: input
    id: roasting
    attributes:
      label: 로스팅
      description: 로스팅 정도를 입력해주세요
    validations:
      required: true

  - type: textarea
    id: bean_details
    attributes:
      label: 원두 상세정보
      description: 원두에 대한 추가 정보를 입력해주세요
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 대표 메뉴
        ⚠️ 아래 양식에 맞춰서 메뉴를 입력해주세요.
        메뉴와 메뉴 사이는 반드시 구분선(---)으로 구분해주세요.

  - type: textarea
    id: menus
    attributes:
      label: 메뉴 목록
      value: |
        이름: 
        가격: 
        이미지: 
        ---
        이름: 
        가격: 
        이미지: 
      description: |
        ✔️ 입력 방법
        1. 이름: [메뉴 이름]
        2. 가격: [숫자만 입력, 상시 변경은 -1]
        3. 이미지: [이미지 URL]
        4. 메뉴 추가시 위 형식을 복사하여 사용 (---로 구분)
    validations:
      required: true
      pattern: "^(이름: .+\\n가격: (-1|[0-9]+)\\n이미지: https?:\\/\\/.+\\n---\\n)*이름: .+\\n가격: (-1|[0-9]+)\\n이미지: https?:\\/\\/.+$"
