spring:
  application:
    name: coffee-api
  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: health, info
  