spring:
  application:
    name: coffee-api

  jackson:
    time-zone: Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://coffee.cp4846ccc9w4.ap-northeast-2.rds.amazonaws.com:3306/coffee?serverTimezone=Asia/Seoul
    username: admin
    password: codebrewadmin
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

#app
app:
  auth:
    token-secret: 8742F6BEC9F62596C2FFEFF9FA0B9E39303554C06F94AB9B85C8090E3EE87F3CF0BE4BFA244C625E3F691321F9CFF38C228C4C3C91105C23919B16F7E40BE4EC
    access-token-expiration-msec: 36000000000
    refresh-token-expiration-msec: 1209600000
cors:
  allow-origin:
    urls: http://localhost:3000, https://25th-web-team-3-fe.vercel.app

springdoc:
  swagger-ui:
    path: swagger
    # "사용해 보기" 섹션이 기본적으로 활성화 되어야 하는지 여부를 제어
    try-it-out-enabled: true
    # filter 검색
    filter: true
    operations-sorter: method
    # ms 단위 표시
    display-request-duration: true
#    supported-submit-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH, TRACE
#    enabled: false
#    query-config-enabled: false
#  api-docs:
#    enabled: false