discord:
  environment: prod
  webhook-url: https://discord.com/api/webhooks/1336771884573917326/ow4SyuP3Ub8wSc02ULAJ98Ex81ZTF7nOHG2ukv4pFMO5hVNuI6wcTpS9aQrdiFmUMuQQ


spring:
  config:
    activate:
      on-profile: prod


  data:
    redis:
      url: redis://coffee-redis.dqrsig.ng.0001.apn2.cache.amazonaws.com:6379

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://coffee.cp4846ccc9w4.ap-northeast-2.rds.amazonaws.com:3306/coffee?serverTimezone=Asia/Seoul
      username: admin
      password: Aupofoffeeis00
    sql:
      init:
        platform: mysql

    jpa:
      hibernate:
        ddl-auto: validate
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true

