package com.coffee.api.cafe.domain

enum class Flavor(
    val displayName: String,
    val category: String,
) {

    FLORAL("플로럴", "Floral"),
    ALMOND("아몬드", "Nutty"),
    CITRUS("시트러스", "Fruit"),
    DARK_CHOCOLATE("다크 초콜릿", "Sweet"),
    ROASTED_NUT("구운호두", "Nutty"),
    BROWN_SUGAR("브라운슈가", "Sweet"),
    RASPBERRY("라즈베리", "Fruit"),
    CHERRY("체리", "Fruit"),
    FULL_BODY("묵직한 바디", "Other"),
    WALNUT("호두", "Nutty"),
    SMOKY("스모키", "Other"),
    ROUND("라운드", "Green"),
    JASMINE("재스민", "Floral"),
    PASSION_FRUIT("패션푸르츠", "Fruit"),
    ORANGE_BLOSSOM("오렌지블라썸", "Floral"),
    BLUEBERRY("블루베리", "Fruit"),
    PLUM("자두", "Fruit"),
    LEMON_PEEL("레몬필", "Sour"),
    ASSAM_TEA("아쌈티", "Spices"),
    SUGAR("설탕", "Sweet"),
    ORANGE("오렌지", "Fruit"),
    HIBISCUS("히비스커스", "Floral"),
    CRANBERRY("크랜베리", "Fruit"),
    MANGO("망고", "Fruit"),
    BAKING_CHOCOLATE("베이킹 초콜릿", "Roasted"),
    ORANGE_PEEL("오렌지필", "Sour"),
    MOLASSES("당밀", "Sweet"),
    ROASTED_HAZELNUT("볶은 헤이즐넛", "Nutty"),
    ALMOND_NUT("아몬드", "Nutty"),
    COCOA_MASS("카카오매스", "Roasted"),
    NECTARINE("넥타린", "Fruit"),
    COCOA_NIBS("카카오닙스", "Roasted"),
    GRAPEFRUIT("자몽", "Fruit"),
    RED_BERRIES("붉은 베리류", "Fruit"),
    APRICOT("살구", "Fruit"),
    CHAMOMILE("캐모마일", "Floral"),
    HONEY("꿀", "Sweet"),
    PEACH("백도", "Fruit"),
    GREEN_GRAPE("청포도", "Fruit"),
    FLORAL_SCENT("꽃향기", "Floral")
}
