package com.coffee.api.cafe.domain

enum class Flavor(
    val displayName: String,
) {

    FLORAL("플로럴"),
    ALMOND("아몬드"),
    CITRUS("시트러스"),
    DARK_CHOCOLATE("다크 초콜릿"),
    ROASTED_NUT("구운호두"),
    BROWN_SUGAR("브라운슈가"),
    RASPBERRY("라즈베리"),
    CHERRY("체리"),
    FULL_BODY("묵직한 바디"),
    WALNUT("호두"),
    SMOKY("스모키"),
    ROUND("라운드"),
    JASMINE("재스민"),
    PASSION_FRUIT("패션푸르츠"),
    ORANGE_BLOSSOM("오렌지블라썸"),
    BLUEBERRY("블루베리"),
    PLUM("자두"),
    LEMON_PEEL("레몬필"),
    ASSAM_TEA("아쌈티"),
    SUGAR("설탕"),
    ORANGE("오렌지"),
    HIBISCUS("히비스커스"),
    CRANBERRY("크랜베리"),
    MANGO("망고"),
    BAKING_CHOCOLATE("베이킹 초콜릿"),
    ORANGE_PEEL("오렌지필"),
    MOLASSES("당밀"),
    ROASTED_HAZELNUT("볶은 헤이즐넛"),
    ALMOND_NUT("아몬드"),
    COCOA_MASS("카카오매스"),
    NECTARINE("넥타린"),
    COCOA_NIBS("카카오닙스"),
    GRAPEFRUIT("자몽"),
    RED_BERRIES("붉은 베리류"),
    APRICOT("살구"),
    CHAMOMILE("캐모마일"),
    HONEY("꿀"),
    PEACH("백도"),
    GREEN_GRAPE("청포도"),
    FLORAL_SCENT("꽃향기")
}
